name: deploy

on:
  schedule:
    - cron: '30 06 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Install pnpm 🚀
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies 🚀
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm update && pnpm install --no-frozen-lockfile

      - name: Setup Node.js 🚀
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build project 🚀
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          pnpm run build

      - name: Upload nakoruru 🚀
        uses: actions/upload-artifact@v3
        with:
          name: nakoruru
          path: dist

      - name: Deploy to gh pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: h7ml/nakoruru
          branch: gh-pages
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          clean: true
          single-commit: true
          git-config-name: h7ml
          git-config-email: h7ml@qq.com
          commit-message: '[Bot] Deploy to GitHub Pages'

      - name: Upload surge service and generate preview URL 🚀
        id: deploy
        run: |
          export GITHUB_SHA=${{ github.sha }}
          export GITHUB_SHA_SUB=${GITHUB_SHA: 0: 7 }
          export DEPLOY_DOMAIN=https://h7ml-$GITHUB_SHA_SUB.surge.sh
          npx surge --project ./dist --domain $DEPLOY_DOMAIN --token ${{ secrets.surge_token }}
          echo the preview URL is $DEPLOY_DOMAIN
          echo "::set-output name=url::$DEPLOY_DOMAIN"

  vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Deploy to vercel 🚀
        uses: amondnet/vercel-action@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.ACCESS_TOKEN }}
          vercel-args: --prod # Optional
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
          github-comment: false
          alias-domains: |
            nakoruru.h7ml.cn
            reactflow-example.h7ml.cn
      - name: Deploy to reactflow-example 🚀
        uses: amondnet/vercel-action@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: --prod # Optional
          github-token: ${{ secrets.GIT_TOKEN }}
          vercel-project-id: prj_Q6U8E1z1WgLrZprWmukpAPxD4SP6
          path: public
          github-comment: false
          alias-domains: |
            nakoruru.vercel.app
    needs: deploy

  surge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Deploy to surge 🚀
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: nakoruru.surge.sh
          project: ./
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

    needs: deploy

  clean:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v2
        with:
          repository: Apocalypsor/Workflows-Cleaner

      - name: Set up Python 🚀
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pipenv 🚀
        run: python -m pip install --upgrade pipenv wheel

      - name: Install dependencies 🚀
        run: |
          pipenv requirements > requirements.txt
          pip install -r requirements.txt

      - name: Clean 🚀
        env:
          GITHUB_REPO: h7ml/nakoruru
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXPIRE_TIME: 12h
        run: python run.py

    needs: surge

  updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Install pnpm 🚀
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies 🚀
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: |
          pnpm install --no-frozen-lockfile
          pnpm types 
          pnpm updates

      - name: Setup Node.js 🚀
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build project 🚀
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          pnpm run format 
          pnpm run build

        if: ${{ success() }}
      - name: Commit and Push files 🚀
        id: commit_and_push
        run: |
          git add package.json pnpm-lock.yaml src/server/
          git config --local user.email "h7ml@qq.com"
          git config --local user.name "h7ml"
          git commit --allow-empty -m "ci: updates dependencies today's hot rank on $(date)" -a
      - name: Push changes  🚀
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}
          force: true
      - name: dependabot 🚀
        uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    needs: clean
